include:
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  DS_DEFAULT_ANALYZERS: "retire.js,gemnasium"
  GIT_SUBMODULE_STRATEGY: recursive

image: registry.gitlab.com/qm64/packer/toolchain:latest

test:
  script:
  - make clean build
  except:
  - master
  artifacts:
    paths:
      - public
    expire_in: 1 day

pages:
  script:
  - make clean build
  artifacts:
    paths:
    - public
  only:
  - master